sudo: required


language: generic


services:
  - docker

before_install:
  - docker build -t devreact -f Dockerfile.dev .

script:
  - docker run -e CI=true devreact npm run test -- --coverage

after_success:
  - echo "test success"